import type { VerifiedMimeType } from "./file-signature";

/**
 * Builds the Storage object key for an uploaded document.
 *
 * THE RULE THIS ENFORCES
 *
 * The key is chosen entirely by the server, from a server-generated UUID and
 * the *validated* MIME type. Nothing the caller sends reaches it — not the
 * filename, not an extension, not a path.
 *
 * That matters more now than it did before. With direct-to-Storage uploads the
 * server mints a signed URL for one specific key and hands it to the browser.
 * A caller-influenced key is therefore a caller-influenced write target: a
 * `../` or an absolute-looking segment would move the object out of the
 * organization's prefix, and that prefix is the *entire* tenant boundary in
 * Storage — `documents_storage_select_member` keys on
 * `(storage.foldername(name))[1]` and nothing else
 * (supabase/migrations/0018_document_storage.sql). There is no
 * `organization_id` column to fall back on.
 *
 * The old path also embedded the user's filename (`<uuid>-<sanitised name>`).
 * Sanitising is a smaller promise than not using it at all, and the filename
 * is still preserved — in `documents.original_filename`, where it is data
 * rather than a path.
 */

/** The only extensions that can be produced, one per accepted type. */
const EXTENSION_FOR_MIME: Record<VerifiedMimeType, string> = {
  "application/pdf": "pdf",
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
};

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function extensionFor(mimeType: VerifiedMimeType): string {
  return EXTENSION_FOR_MIME[mimeType];
}

/**
 * `<organizationId>/<uuid>.<ext>`.
 *
 * Both identifiers are asserted to be UUIDs rather than trusted. `objectId` is
 * generated by the caller (`crypto.randomUUID()`) so the check should never
 * fire; `organizationId` has been through Zod and a membership lookup, so that
 * one should never fire either. They are here because the cost of being wrong
 * is a cross-tenant write, and a thrown error is a much better outcome than a
 * successfully created signed URL pointing somewhere else.
 */
export function storageKeyFor(organizationId: string, objectId: string, mimeType: VerifiedMimeType): string {
  if (!UUID.test(organizationId)) throw new Error("Refusing to build a storage key from a non-UUID organization id.");
  if (!UUID.test(objectId)) throw new Error("Refusing to build a storage key from a non-UUID object id.");

  return `${organizationId}/${objectId}.${extensionFor(mimeType)}`;
}

/**
 * Confirms a stored key still belongs to the organization acting on it.
 *
 * Read back from the database rather than constructed, so this guards the
 * case where a row's `storage_path` is not what this module would have
 * produced — a legacy row, or a row that was tampered with.
 */
export function isKeyOwnedBy(storagePath: string, organizationId: string): boolean {
  if (!UUID.test(organizationId)) return false;
  const segments = storagePath.split("/");
  if (segments.length !== 2) return false;
  return segments[0] === organizationId && segments[1].length > 0 && !segments[1].includes("..");
}
