import type { Metadata } from "next";
import Link from "next/link";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { Reveal } from "@/components/marketing/reveal";

export const metadata: Metadata = {
  title: "Privacy — Countorra",
  description: "How Countorra collects, uses, stores, and protects your data.",
};

const LAST_UPDATED = "September 5, 2026";

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="flex flex-col gap-3 border-t border-border-subtle pt-8">
      <h2 className="text-2xl font-semibold tracking-[-0.01em] text-ink sm:text-[28px]">{title}</h2>
      <div className="flex max-w-[70ch] flex-col gap-3 text-[15px] leading-[1.7] text-text-secondary">{children}</div>
    </section>
  );
}

/**
 * Real privacy policy (DESIGN brief §2), not AI-generated filler: every
 * claim below is checked against what the codebase actually does —
 * Supabase for auth/database/storage (src/server/supabase), Anthropic for
 * the AI assistant only (src/domain/ai/providers/anthropic.ts), no OCR
 * provider (src/domain/documents has no provider wired in), no payment
 * provider (src/domain/billing has types only), no analytics library in
 * package.json, no localStorage use anywhere in src/. Bracketed fields are
 * explicit configuration placeholders per the brief — replace them with
 * real business/legal details before this is treated as binding.
 */
export default function PrivacyPage() {
  return (
    <MarketingShell>
      <section className="mx-auto max-w-[760px] px-6 py-16 lg:px-10 lg:py-24">
        <Reveal>
          <p className="text-[13px] text-text-tertiary">Last updated {LAST_UPDATED}</p>
          <h1 className="font-serif font-normal tracking-[0] mt-2 text-[32px] leading-[40px] text-ink">Privacy Policy</h1>
          <p className="mt-5 max-w-[70ch] text-[15px] leading-[1.7] text-text-secondary">
            This policy explains what information Countorra collects, how it&apos;s used, who it&apos;s shared with, and
            what control you have over it. Countorra is early-stage software — this policy describes the product as it
            actually works today, not a future roadmap.
          </p>

          <div className="mt-6 rounded-md border border-border-subtle bg-surface-sunken p-4">
            <p className="text-[13px] leading-[1.6] text-text-secondary">
              <strong className="text-text-primary">Configuration notice.</strong> Bracketed fields below (legal entity
              name, registered address, governing jurisdiction, contact address) are placeholders. Replace them with real
              business details in{" "}
              <code className="rounded-[4px] bg-surface px-1 py-0.5 font-numeric text-[12px]">
                src/app/privacy/page.tsx
              </code>{" "}
              before this policy is presented as binding to real users.
            </p>
          </div>
        </Reveal>

        <div className="mt-10 flex flex-col gap-8">
          <Section id="who-we-are" title="1. Who this policy covers">
            <p>
              This policy applies to Countorra, operated by <strong className="text-text-primary">[Company Legal Name]</strong>,{" "}
              <strong className="text-text-primary">[Company Registered Address]</strong>. If you have questions about this
              policy or your data, contact <strong className="text-text-primary">[privacy@yourdomain.example]</strong>.
            </p>
          </Section>

          <Section id="information-we-collect" title="2. Information we collect">
            <p>We collect information you give us directly, and information generated by your use of the product:</p>
            <ul className="list-disc pl-5">
              <li>
                <strong className="text-text-primary">Account information</strong> — your name and email address, collected
                when you create an account. Accounts are email and password only, managed by Supabase Auth.
              </li>
              <li>
                <strong className="text-text-primary">Authentication and session data</strong> — a session token stored in
                an HTTP-only cookie so you stay signed in, managed entirely by Supabase Auth. We never see or store your
                password in plain text; Supabase hashes it.
              </li>
              <li>
                <strong className="text-text-primary">Financial information you enter</strong> — accounts, transactions,
                income and expenses, invoices, and customers you manually create in the product. Countorra does not
                connect to your bank and does not import transactions automatically — every figure is entered by you or a
                member of your organization.
              </li>
              <li>
                <strong className="text-text-primary">Uploaded documents</strong> — files you upload (receipts, invoices,
                tax forms) are stored in a private Supabase Storage bucket, isolated to your organization.
              </li>
              <li>
                <strong className="text-text-primary">AI conversations and results</strong> — messages you send to the AI
                assistant, and the assistant&apos;s responses, are stored so your conversation history persists across
                sessions.
              </li>
              <li>
                <strong className="text-text-primary">Usage and security information</strong> — a security-relevant audit
                log of sensitive actions (e.g. AI-initiated changes, membership changes) tied to your organization, used
                for security and troubleshooting, never for advertising.
              </li>
            </ul>
          </Section>

          <Section id="cookies" title="3. Cookies and local storage">
            <p>
              Countorra uses one type of cookie: the authentication session cookie set by Supabase Auth, required for
              you to stay signed in. This is strictly functional — we do not use advertising cookies, tracking pixels, or
              third-party analytics cookies. The product does not currently store any personal data in your browser&apos;s
              local storage.
            </p>
          </Section>

          <Section id="how-we-use-it" title="4. How we use your information">
            <ul className="list-disc pl-5">
              <li>To operate the product: authenticate you, scope your data to your organization, and render your dashboard, transactions, invoices, and reports.</li>
              <li>To power the AI assistant: when you ask it a question, your message and the specific financial records needed to answer it are sent to our AI provider (see §6) to generate a response.</li>
              <li>To secure the product: detect and investigate suspicious activity, and enforce the confirmation step required before any AI-suggested change to your records is applied.</li>
              <li>To communicate with you: respond to support requests and send essential account/security notices.</li>
            </ul>
            <p>We do not sell your data, and we do not use your financial data to train AI models.</p>
          </Section>

          <Section id="how-we-store-it" title="5. How your data is stored and protected">
            <p>
              Your data is stored in Supabase-managed Postgres, Auth, and Storage infrastructure. Every table containing
              your data enforces row-level security (RLS) scoped to your organization, so another organization&apos;s
              members cannot read or write your records at the database level — this is enforced by the database itself,
              not only by application code. Connections to the product are encrypted in transit (HTTPS/TLS). Uploaded
              documents live in a private storage bucket; access requires a short-lived signed URL generated only for an
              authorized member of your organization. See <Link href="/security" className="text-accent hover:underline">Security</Link> for more detail.
            </p>
          </Section>

          <Section id="third-parties" title="6. Third-party service providers">
            <p>We share the minimum data necessary with a small number of infrastructure and AI providers:</p>
            <ul className="list-disc pl-5">
              <li>
                <strong className="text-text-primary">Supabase</strong> — our database, authentication, and file storage
                provider. All account, financial, document, and conversation data described above is stored with Supabase.
              </li>
              <li>
                <strong className="text-text-primary">Anthropic</strong> — when you use the AI assistant (&ldquo;Ask your
                money&rdquo;), your message and the relevant financial data needed to answer it are sent to Anthropic&apos;s API
                to generate a response. Anthropic processes this data to return a response; it is not sent for any other
                purpose.
              </li>
            </ul>
            <p>
              We do <strong className="text-text-primary">not</strong> currently use a social or single sign-on provider, a
              document/OCR extraction provider, a payment processor, or any analytics or advertising platform. If any of
              these are introduced in the future, this policy will be updated first, and you will be notified.
            </p>
          </Section>

          <Section id="retention" title="7. Data retention">
            <p>
              Your data is retained for as long as your account or organization is active. If you delete an organization,
              its associated transactions, invoices, documents, and AI conversations are removed. Security audit log
              entries are retained separately and are append-only — they cannot be edited or deleted by any application
              action, including by us, which is what makes them useful as a tamper-evident security record.
            </p>
          </Section>

          <Section id="deletion" title="8. Account deletion and your data">
            <p>
              Self-serve account deletion is not yet built into the product. To request deletion of your account and
              associated data, contact <strong className="text-text-primary">[privacy@yourdomain.example]</strong>. We will
              verify your identity and delete your data within a reasonable timeframe, except where we&apos;re required to
              retain limited records for legal or security purposes.
            </p>
          </Section>

          <Section id="your-rights" title="9. Your rights">
            <p>You can, at any time:</p>
            <ul className="list-disc pl-5">
              <li>View and correct your profile and organization details in Settings.</li>
              <li>Request a copy of your data by contacting us (self-serve export is not yet available).</li>
              <li>Request deletion of your account, as described above.</li>
              <li>Ask us what data we hold about you.</li>
            </ul>
            <p>
              Depending on where you live, you may have additional rights under laws such as the GDPR or CCPA. Contact{" "}
              <strong className="text-text-primary">[privacy@yourdomain.example]</strong> to exercise them.
            </p>
          </Section>

          <Section id="international" title="10. International data processing">
            <p>
              Our infrastructure providers (Supabase, Anthropic) may process data in countries other than your own. Where
              this involves transferring data out of the European Economic Area, UK, or other regions with data-transfer
              requirements, we rely on the safeguards those providers make available. Our own registered jurisdiction is{" "}
              <strong className="text-text-primary">[Governing Jurisdiction]</strong>.
            </p>
          </Section>

          <Section id="children" title="11. Children's privacy">
            <p>Countorra is not directed at children and is not intended for use by anyone under 18.</p>
          </Section>

          <Section id="changes" title="12. Changes to this policy">
            <p>
              If we make a material change to this policy, we&apos;ll update the date at the top of this page and, where
              appropriate, notify you directly.
            </p>
          </Section>

          <Section id="contact" title="13. Contact">
            <p>
              Questions about this policy or your data: <strong className="text-text-primary">[privacy@yourdomain.example]</strong>,{" "}
              <strong className="text-text-primary">[Company Registered Address]</strong>.
            </p>
          </Section>
        </div>
      </section>
    </MarketingShell>
  );
}
